### ISSUE TITLE
Checkpointing optimizers

### ISSUE THREAD

**Issue by fabvio** [vpj/lab#14]
Hi,
I am working with your framework. First of all, great job. It really saved me from the usual research mess :)
I have some questions about the checkpointing. I've seen that each layer is saved in a .npy format. However, this does not work for other objects that are based on `state_dict`, for example optimizers. For long trainings they should be saved with the model, since we don't want to retrain the whole model from scratch. I've looked into your checkpointing strategy [here](https://github.com/vpj/lab/blob/master/lab/experiment/pytorch.py#L41). Do you see any significant problem if instead saving all layers in .npy files we directly save the `state_dict`?

**Comment by fabvio** [comment]
I also opened a pull request to show what I mean. Obviously you designed this and you'll know way better than me what's going on under the hood, so I may not see every problem that comes with my approach. What do you think?

**Comment by vpj** [comment]
Hey, thanks for raising this and the pull request. Your approach makes perfect sense.

The decision to save to numpy was done way back when **lab** was for Tensorflow, and I left it when we added PyTorch support and later dropped Tensorflow support (because none of the **lab** users seemed to be using Tensorflow).

I have personally being resetting optimizers (to save checkpoint sizes and because it didn't have a huge effect on the tasks I was working on) so I didn't come across this problem yet. Saving as `state_dict` directly is both simpler and probably future proof to any changes PyTorch might make too.

I'll merge you request, ASAP. I just want to add some backward compatibility to load back old checkpoints saved in numpy formats. I will close the issue once we merge it.

Thanks again

**Comment by fabvio** [comment]
Great! In the checkpoint saving it could be needed to load also the current epoch/iteration. I think it could be saved in the .json file, but I don't know which could be the best practise to load that if we want to resume an interrupted training. Do you have anything in mind?

**Comment by vpj** [comment]
Right now it picks the global step from the checkpoint. The checkpoint folder name is the step at which it was saved

**Comment by fabvio** [comment]
Got it! Ok, it's all I could desire about checkpointing ahah.
I'll close the issue.
